# Generated by Django 5.1.5 on 2025-03-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="owner",
        ),
    ]
